/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type OutboxStatus = 'DEAD' | 'PENDING' | 'SUCCESS';

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Inbox {
  created_at: Generated<Timestamp>;
  event_id: string;
  processed_at: Timestamp | null;
  stage: Generated<string | null>;
  success: Generated<boolean>;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  event_id: string;
  id: Generated<string>;
  payload: Json | null;
  user_id: string;
}

export interface Outbox {
  created_at: Generated<Timestamp>;
  event_id: string;
  id: Generated<string>;
  next_attempt_at: Timestamp | null;
  payload: Json;
  retries: Generated<number | null>;
  status: Generated<OutboxStatus>;
}

export interface UserNotifications {
  email: string;
  phone_number: Generated<string | null>;
  receive_email_notifications: Generated<boolean>;
  receive_important_messages: Generated<boolean>;
  receive_not_important_messages: Generated<boolean>;
  receive_notifications: Generated<boolean>;
  receive_phone_notifications: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface DB {
  inbox: Inbox;
  notifications: Notifications;
  outbox: Outbox;
  user_notifications: UserNotifications;
}
